#!/bin/bash
# This docker image is used for testing the JDBC metadata parsing for Oracle
# Them image must be stared manually before the tests are run.
docker run --rm -p 1521:1521 -p 8080:8080 --env SCHEMAS=PRU  -v "$(pwd)"/docker:/u01/scripts/batch --name ora carloscastillo/rgt-oracle-xe-11g
