name: dev # Unique name for data ingestion
group: edh_employee_db # Associated AD group for ingestion
databaseType: mysql # Database type must be mysql, oracle, mssql, hana, or teradata
schema: employees # Database schema to ingest
jdbcUrl: "jdbc:mysql://localhost:3306/employees" # JDBC Url for connecting to database
username: employee # Database user name
objectType: view # Database object type to be ingested must be either table or view
# tables: # Optionally add a whitelisting of tables to ingest
#   - employee
metadata: # Metadata map to be applied to every table's tblproperties. https://www.cloudera.com/documentation/enterprise/latest/topics/impala_create_table.html
  SOURCE: employee database # Source database identifier
  LOAD_FREQUENCY: Daily # Frequency of data ingestion
  CONTACT: developer@phdata.io # Distribution list for data owners
hadoopUser: ps_dev_employee # Hadoop user recommended to use a process account
passwordFile: hdfs://user/developer/.employee_db_password # Location of sqoop's password file recommended HDFS location
stagingDatabase:
  name: edh_employee_staging
  path: hdfs://user/developer/staging/db
rawDatabase:
  name: edh_employee_raw
  path: hdfs://user/developer/raw/db